services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: local_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Seoul
      - TZ=Asia/Seoul
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - NODES_EXCLUDE=[]
    volumes:
      - local_n8n_data:/home/node/.n8n

volumes:
  local_n8n_data: